# Generated by Django 5.2.3 on 2025-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', max_length=20, null=True),
        ),
    ]
