# Generated by Django 5.2.3 on 2025-06-19 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(upload_to='material/', verbose_name='Select file'),
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
    ]
